{{/*
SPDX-FileCopyrightText: Copyright (c) 2026 Red Hat, Inc. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.temporalPostgresql.enabled }}
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: temporal-pg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-infra-controller-cloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
spec:
  postgresVersion: 18
  instances:
    - name: instance1
      replicas: {{ .Values.temporalPostgresql.instances | default 1 }}
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.temporalPostgresql.storage.size | default "5Gi" }}
  users:
    - name: temporal
      databases:
        - temporal
        - temporal_visibility
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi
{{- end }}
