# SPDX-FileCopyrightText: Copyright (c) 2026 Red Hat, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Fix secret key name in nico-api Deployment: Crunchy uses 'user' not 'username'.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nico-api
spec:
  template:
    spec:
      containers:
        - name: nico-api
          env:
            - name: DATASTORE_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: nico-site-pg-pguser-nico
