{{/*
SPDX-FileCopyrightText: Copyright (c) 2026 Red Hat, Inc. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nico-rest-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-infra-controller-cloud.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: nico-rest-api
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
{{- if .Values.keycloakInstance.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak
  namespace: {{ .Values.keycloakInstance.namespace }}
  labels:
    {{- include "nvidia-infra-controller-cloud.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: keycloak-service
  port:
    targetPort: https
  tls:
    termination: passthrough
{{- end }}
