{{/*
SPDX-FileCopyrightText: Copyright (c) 2026 Red Hat, Inc. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: temporal-server-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nvidia-infra-controller-cloud-infra.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  secretName: temporal-server-certs
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
    - temporal-frontend
    - temporal-frontend.{{ .Release.Namespace }}
    - temporal-frontend.{{ .Release.Namespace }}.svc
    - temporal-frontend.{{ .Release.Namespace }}.svc.cluster.local
    - temporal-history
    - temporal-matching
    - temporal-worker
    - interservice.server.temporal.local
    - cloud.interservice.server.temporal.local
  uris:
    - "spiffe://nico.local/{{ .Release.Namespace }}/sa/temporal"
  issuerRef:
    name: nico-rest-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
