# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Build stage
# hadolint ignore=DL3007
FROM registry.access.redhat.com/ubi10/go-toolset:latest AS builder
# hadolint ignore=DL3002
USER 0
ENV CGO_ENABLED=0
WORKDIR /workspace

COPY go.mod go.sum ./
COPY sdk/standard/go.mod ./sdk/standard/
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    go mod download

COPY proto/ ./proto/
COPY common/ ./common/
COPY db/ ./db/
COPY ipam/ ./ipam/

# hadolint ignore=DL3002
USER 0
ENV CGO_ENABLED=0
WORKDIR /workspace/db
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    --mount=type=cache,target=/root/.cache/go-build   \
    go build \
        -ldflags "-extldflags '-static' -w -s" \
        -o /app/migrations \
        ./cmd/migrations

# Runtime stage
# hadolint ignore=DL3007
FROM registry.access.redhat.com/ubi10/ubi-micro:latest

WORKDIR /app

COPY --from=builder /app/migrations /app/migrations

USER 1001

CMD ["/app/migrations", "db", "init_migrate"]
