# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Build stage
# hadolint ignore=DL3007
FROM registry.access.redhat.com/ubi10/go-toolset:latest AS builder
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# hadolint ignore=DL3002
USER 0
ENV CGO_ENABLED=0
WORKDIR /workspace

COPY go.mod go.sum ./
COPY sdk/standard/go.mod ./sdk/standard/
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    go mod download

COPY proto/ ./proto/
COPY api/ ./api/
COPY common/ ./common/
COPY auth/ ./auth/
COPY db/ ./db/
COPY workflow/ ./workflow/
COPY site-workflow/ ./site-workflow/
COPY ipam/ ./ipam/
COPY site-manager/ ./site-manager/
COPY cert-manager/ ./cert-manager/
COPY openapi/ ./openapi/
COPY cli/ ./cli/

RUN mkdir -p /var/secrets/temporal/certs

# hadolint ignore=DL3002
USER 0
ENV CGO_ENABLED=0
WORKDIR /workspace/api
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    --mount=type=cache,target=/root/.cache/go-build   \
    VERSION=$(grep -v '^#' /workspace/VERSION | tr -d '[:space:]' 2>/dev/null || echo "dev") && \
    BUILD_TIME=$(date +"%Y-%m-%d %H:%M:%S") && \
    go build \
        -ldflags "-extldflags '-static' -w -s \
                  -X 'github.com/NVIDIA/infra-controller-rest/api/pkg/metadata.Version=${VERSION}' \
                  -X 'github.com/NVIDIA/infra-controller-rest/api/pkg/metadata.BuildTime=${BUILD_TIME}'" \
        -o /app/api \
        ./cmd/api

# hadolint ignore=DL3002
USER 0
ENV CGO_ENABLED=0
WORKDIR /workspace/cli
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    --mount=type=cache,target=/root/.cache/go-build   \
    go build \
        -ldflags "-extldflags '-static' -w -s" \
        -o /app/nicocli \
        ./cmd/cli

# Runtime stage
# hadolint ignore=DL3007
FROM registry.access.redhat.com/ubi10/ubi-micro:latest

WORKDIR /app

COPY --from=builder /app/api /app/api
COPY --from=builder /app/nicocli /app/nicocli
COPY --from=builder /var/secrets/temporal/certs /var/secrets/temporal/certs

USER 1001

EXPOSE 8388

ENTRYPOINT ["/app/api"]
