# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Build stage
# hadolint ignore=DL3007
FROM registry.access.redhat.com/ubi10/go-toolset:latest AS builder
# hadolint ignore=DL3002
USER 0
ENV CGO_ENABLED=0
WORKDIR /workspace

COPY go.mod go.sum ./
COPY sdk/standard/go.mod ./sdk/standard/
COPY proto/ ./proto/
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    go mod download

COPY cert-manager/ ./cert-manager/

# hadolint ignore=DL3002
USER 0
ENV CGO_ENABLED=0
WORKDIR /workspace/cert-manager
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    --mount=type=cache,target=/root/.cache/go-build   \
    go build \
        -ldflags "-extldflags '-static' -w -s" \
        -o /app/credsmgr \
        ./cmd/credsmgr

# Runtime stage
# hadolint ignore=DL3007
FROM registry.access.redhat.com/ubi10/ubi-micro:latest

WORKDIR /app

COPY --from=builder /app/credsmgr /app/credsmgr

USER 1001

EXPOSE 8080

ENTRYPOINT ["/app/credsmgr"]
