# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Build stage
# hadolint ignore=DL3007
FROM registry.access.redhat.com/ubi10/go-toolset:latest AS builder
ENV CGO_ENABLED=0

# hadolint ignore=DL3002
USER 0
WORKDIR /workspace

COPY go.mod go.sum ./
COPY sdk/standard/go.mod ./sdk/standard/
COPY proto/ ./proto/
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    go mod download

COPY common/ ./common/
COPY db/ ./db/
COPY flow/ ./flow/

# hadolint ignore=DL3002
USER 0
WORKDIR /workspace/flow
RUN --mount=type=cache,target=/root/go/pkg/mod   \
    --mount=type=cache,target=/root/.cache/go-build   \
    go build \
        -ldflags "-extldflags '-static' -w -s" \
        -o /app/flow \
        .

# Runtime stage
# hadolint ignore=DL3007
FROM registry.access.redhat.com/ubi10/ubi-micro:latest

WORKDIR /app

COPY --from=builder /app/flow /app/flow

USER 1001

EXPOSE 50051

ENTRYPOINT ["/app/flow", "serve"]
